services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_PASSWORD=supersecurepassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "server-data:/var/lib/postgresql/data/pgdata"
  server:
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - "3001:3001"
    expose:
      - 3001
    links:
      - postgres
volumes:
  server-data: {}
